### ISSUE TITLE
A project not yet using the architecture style fails

### ISSUE THREAD

**Issue by jamietanna** [xmolecules/jmolecules-integrations#99]

**Comment by jamietanna** [comment]
I've recently migrated a couple of codebases to jMolecules-codified architectures, and found that the first thing I reach for is a test to capture what is being done.

In the case that my project has pulled the jMolecules dependencies, adds the ArchUnit test to enforce a rule, but then doesn't have any annotations, I'd want the test to fail to give me the feedback that I've implemented it wrong.

Alternatively, I could have a complete codebase using the architecture style, remove the annotations, and the test would likely still pass, despite the annotations being gone, and nothing enforcing i.e. Onion rings?

**Comment by odrotbohm** [comment]
What I am still not getting is what we would be supposed to report under which conditions? No concepts identified at all? Okay, we could report that. But then what about if you just annotate a single package with an architectural rule. It's still just as uncompletely-expressed architecture as before, but we can't really report anything "missing".

I.e. how much architecture you want to express in your codebase can vary from project to project, and we're not in the business of verifying completeness of that. First – and foremost –  because it's impossible to define what constitutes "complete" or even just "enough".

I am inclined to close this as won't fix as the current behavior is in line with our design ideas: we verify the architectural ideas that *you express*, not the ones missing.
